settings:
  num_classes: 4
  size: [1280,720]
  checkpoint: "./models/deepsort/deep/checkpoint/ckpt.t7"
  cam:
    cam_01: 
      video: '/content/main/datasets/aic-hcmc2020/videos/cam_01.mp4'
      boxes: '/content/drive/My Drive/results/AIC HCMC 2020/boxes/cam_01'
      zone: '/content/main/datasets/aic-hcmc2020/zones/zones_movement_paths/cam_01.json'
      tracking_config:
        MAX_DIST: 0.2
        MIN_CONFIDENCE: 0.5
        NMS_MAX_OVERLAP: 0.9
        MAX_IOU_DISTANCE: 0.7
        MAX_AGE: 40
        N_INIT: 7
        NN_BUDGET: 60
    cam_02:
      REID_CKPT: "./models/deepsort/deep/checkpoint/ckpt.t7"
      MAX_DIST: 0.2
      MIN_CONFIDENCE: 0.3
      NMS_MAX_OVERLAP: 0.5
      MAX_IOU_DISTANCE: 0.7
      MAX_AGE: 40
      N_INIT: 5
      NN_BUDGET: 60
    cam_03:
      video:
      boxes:
      zone:
      tracking_config:
        MAX_DIST: 0.2
        MIN_CONFIDENCE: 0.3
        NMS_MAX_OVERLAP: 0.5
        MAX_IOU_DISTANCE: 0.7
        MAX_AGE: 40
        N_INIT: 5
        NN_BUDGET: 60